security:
    providers:
        in_memory:
            memory:
                users:
                    popov:
                        password: $2y$12$yL3Vp74Z0BMxVLSLNmuUzOED8HOPYJYOFfYIdiB/C1DKpJEnSDcqS
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12