index:
    path: /
    controller: App\Controller\DefaultController::index
portfolio:
    path: /portfolio
    controller: App\Controller\DefaultController::showPortfolio
stylePortfolio:
    path: /portfolio/style
    controller: App\Controller\DefaultController::showStylePortfolio
muaPortfolio:
    path: /portfolio/makeup
    controller: App\Controller\DefaultController::showMuaPortfolio
sneakPeakPortfolio:
    path: /portfolio/sneakPeak
    controller: App\Controller\DefaultController::showSneakPeakPortfolio
admin:
    path: /admin
    controller: App\Controller\Admin\AdminController::showAdminPanel
is_posted:
    path: /admin/is_posted
    controller: App\Controller\Admin\AdminController::setIsPosted
editPhotoshoot:
    path: /admin/edit/{id}
    controller: App\Controller\Admin\AdminController::editPhotoshoot
deletePhotoshoot:
    path: /admin/delete/{id}
    controller: App\Controller\Admin\AdminController::deletePhotoshoot
addPhotoshoot:
    path: /admin/addPhotoshoot
    controller: App\Controller\Admin\AdminController::addPhotoshoot
editPhotoshootImages:
    path: /admin/editImages/{id}
    controller: App\Controller\Admin\AdminController::editPhotoshootImages
deleteImage:
    path: /admin/deleteImage/{id}
    controller: App\Controller\Admin\AdminController::deleteImage
addCategory:
    path: /admin/addCategory
    controller: App\Controller\Admin\AdminController::addCategory
adminStylePortfolio:
    path: /admin/style
    controller: App\Controller\Admin\AdminController::adminStylePortfolio
adminMuaPortfolio:
    path: /admin/makeup
    controller: App\Controller\Admin\AdminController::adminMuaPortfolio
adminSneakPeakPortfolio:
    path: /admin/sneakPeak
    controller: App\Controller\Admin\AdminController::adminSneakPeakPortfolio
editIndexInfo:
    path: /admin/editIndex
    controller: App\Controller\Admin\AdminController::editIndexInfo
sendMail:
    path: /sendMail
    controller: App\Controller\DefaultController::sendMail